[package]
name = "percolator-common"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["lib"]
doctest = false

[dependencies]
pinocchio = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }

[features]
default = []
